dist: buster

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/1.0.0/bazel_1.0.0-linux-x86_64.deb
  - sudo dpkg -i bazel_1.0.0-linux-x86_64.deb

script:
  - bazel test --test_output=errors //...